name: 'Setup Bun with Caching'
description: 'Sets up Bun with dependency caching for faster workflow runs'

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'
  frozen-lockfile:
    description: 'Use frozen lockfile for installation'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          bun install --frozen-lockfile
        else
          bun install
        fi
